# Generated by Django 4.2.7 on 2023-11-09 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0003_alter_classmate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='firstname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters are allowed in the name.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='lastname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters are allowed in the name.', regex='^[a-zA-Z]+$')]),
        ),
    ]
