# Generated by Django 4.2.7 on 2023-11-09 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0004_alter_classmate_firstname_alter_classmate_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='firstname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid Input:Only letters are allowed in the name.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='classmate',
            name='lastname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid Input:Only letters are allowed in the name.', regex='^[a-zA-Z]+$')]),
        ),
    ]
